### ISSUE TITLE
May I ask when will the code for demo running on RGBD stream data be released, thank you.

### ISSUE THREAD

**Issue by RongkunYang** [xuxw98/ESAM#18]

**Comment by XXXCARREY** [comment]
Hello, we have provided the visualization code, and you can refer to the `demo.md` for visualizing the segmentation results of a single scene. Additionally, if you would like to implement the functionality for frame-by-frame input and visualization, feel free to modify the model code logic. You can try moving the loop inside the `predict` function of `ScanNet200MixFormer3D_Online` to the outside so that it processes only one frame of input at a time, and then refer to the visualization code for the visualization.

**Comment by RongkunYang** [comment]
OK, thank you very much, I will try this.

**Comment by g-h-anna** [comment]
> OK, thank you very much, I will try this.

Hi @RongkunYang , have you managed to modify the code for streaming?
