### ISSUE TITLE
ValueError: cannot reshape array of size 712080 into shape (60,20000,3)

### ISSUE THREAD

**Issue by sysu19351158** [xuxw98/ESAM#20]
Thank you for your great work! I meet an error when I run the online_demo.py. The command I use is 

CUDA_VISIBLE_DEVICES=7 python vis_demo/online_demo.py --config configs/ESAM-E/ESAM-E_online_scannet.py --checkpoint ./work_dirs/tmp/ESAM-E_online_epoch_128.pth

Then I meet the error below:

Traceback (most recent call last):
  File "/data0/xxh/online_semantic_segmentation/ESAM/vis_demo/online_demo.py", line 138, in <module>
    main()
  File "/data0/xxh/online_semantic_segmentation/ESAM/vis_demo/online_demo.py", line 115, in main
    points_color = pred_seg_color.reshape(points.shape[0], points.shape[1], 3)
ValueError: cannot reshape array of size 712080 into shape (60,20000,3)

Did I use the command right? Should I use another model?

**Comment by XXXCARREY** [comment]
Hello! We have updated the model code in the `mixformer3d.py` file while uploading the demo code, allowing it to provide per-frame segmentation results instead of the final interpolation to reconstructed point cloud for performance metric calculation. The issue you encountered may have been caused by not updating the model code. If you still face problems after the update, please feel free to let us know!

**Comment by sysu19351158** [comment]
Thank you for your quick answer! But the error is still the same.

**Comment by XXXCARREY** [comment]
We're sorry that we've found a typo in the `online_demo.py` file at [line 97](https://github.com/xuxw98/ESAM/blob/main/vis_demo/online_demo.py#L97). The original `model.map_to_ori_pcd` should be changed to `model.map_to_rec_pcd`. The code has been corrected now.

**Comment by sysu19351158** [comment]
That's right! Thank you very much. Now it runs successfully.
