### ISSUE TITLE
Train&Test on my own dataset

### ISSUE THREAD

**Issue by MYM181** [xuxw98/ESAM#30]
Hi, thanks for your great work!
I'm wondering if I can test the model (for example trained on ScanNet) on my own data? How to figure it out? 
I'm trying to test the model's generalizability.
I'm not very clear about it. Hope you give me some extra information.
Thanks!

**Comment by xuxw98** [comment]
Hi, thanks for your interest! For testing on custom data, you can try our visualization [demo](https://github.com/xuxw98/ESAM/blob/main/docs/demo.md). You can organize your data to have the same format with ScanNet then run the script for prediction.

**Comment by g-h-anna** [comment]
> Hi, thanks for your great work! I'm wondering if I can test the model (for example trained on ScanNet) on my own data? How to figure it out? I'm trying to test the model's generalizability. I'm not very clear about it. Hope you give me some extra information. Thanks!

Hi @MYM181 !
Have you managed to test it on your data?
If the folders "color", "depth" and "pose" are prepared within a folder named "custom_data" (which is next to "scannet" folder), how can you call the vis_demo for those folders instead of scannet?
I checked config, but not sure about what to change/extend, as there scannet-like lines in all parts.

Thanks in advance!
